# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.28

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /mnt/c/Development/Projects/C++_BlackJack

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /mnt/c/Development/Projects/C++_BlackJack

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/c/Development/Projects/C++_BlackJack/CMakeFiles /mnt/c/Development/Projects/C++_BlackJack//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/c/Development/Projects/C++_BlackJack/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named BlackjackAI

# Build rule for target.
BlackjackAI: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 BlackjackAI
.PHONY : BlackjackAI

# fast build rule for target.
BlackjackAI/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BlackjackAI.dir/build.make CMakeFiles/BlackjackAI.dir/build
.PHONY : BlackjackAI/fast

src/Card.o: src/Card.cpp.o
.PHONY : src/Card.o

# target to build an object file
src/Card.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BlackjackAI.dir/build.make CMakeFiles/BlackjackAI.dir/src/Card.cpp.o
.PHONY : src/Card.cpp.o

src/Card.i: src/Card.cpp.i
.PHONY : src/Card.i

# target to preprocess a source file
src/Card.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BlackjackAI.dir/build.make CMakeFiles/BlackjackAI.dir/src/Card.cpp.i
.PHONY : src/Card.cpp.i

src/Card.s: src/Card.cpp.s
.PHONY : src/Card.s

# target to generate assembly for a file
src/Card.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BlackjackAI.dir/build.make CMakeFiles/BlackjackAI.dir/src/Card.cpp.s
.PHONY : src/Card.cpp.s

src/Deck.o: src/Deck.cpp.o
.PHONY : src/Deck.o

# target to build an object file
src/Deck.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BlackjackAI.dir/build.make CMakeFiles/BlackjackAI.dir/src/Deck.cpp.o
.PHONY : src/Deck.cpp.o

src/Deck.i: src/Deck.cpp.i
.PHONY : src/Deck.i

# target to preprocess a source file
src/Deck.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BlackjackAI.dir/build.make CMakeFiles/BlackjackAI.dir/src/Deck.cpp.i
.PHONY : src/Deck.cpp.i

src/Deck.s: src/Deck.cpp.s
.PHONY : src/Deck.s

# target to generate assembly for a file
src/Deck.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BlackjackAI.dir/build.make CMakeFiles/BlackjackAI.dir/src/Deck.cpp.s
.PHONY : src/Deck.cpp.s

src/Hand.o: src/Hand.cpp.o
.PHONY : src/Hand.o

# target to build an object file
src/Hand.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BlackjackAI.dir/build.make CMakeFiles/BlackjackAI.dir/src/Hand.cpp.o
.PHONY : src/Hand.cpp.o

src/Hand.i: src/Hand.cpp.i
.PHONY : src/Hand.i

# target to preprocess a source file
src/Hand.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BlackjackAI.dir/build.make CMakeFiles/BlackjackAI.dir/src/Hand.cpp.i
.PHONY : src/Hand.cpp.i

src/Hand.s: src/Hand.cpp.s
.PHONY : src/Hand.s

# target to generate assembly for a file
src/Hand.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BlackjackAI.dir/build.make CMakeFiles/BlackjackAI.dir/src/Hand.cpp.s
.PHONY : src/Hand.cpp.s

src/QLearner.o: src/QLearner.cpp.o
.PHONY : src/QLearner.o

# target to build an object file
src/QLearner.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BlackjackAI.dir/build.make CMakeFiles/BlackjackAI.dir/src/QLearner.cpp.o
.PHONY : src/QLearner.cpp.o

src/QLearner.i: src/QLearner.cpp.i
.PHONY : src/QLearner.i

# target to preprocess a source file
src/QLearner.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BlackjackAI.dir/build.make CMakeFiles/BlackjackAI.dir/src/QLearner.cpp.i
.PHONY : src/QLearner.cpp.i

src/QLearner.s: src/QLearner.cpp.s
.PHONY : src/QLearner.s

# target to generate assembly for a file
src/QLearner.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BlackjackAI.dir/build.make CMakeFiles/BlackjackAI.dir/src/QLearner.cpp.s
.PHONY : src/QLearner.cpp.s

src/Renderer.o: src/Renderer.cpp.o
.PHONY : src/Renderer.o

# target to build an object file
src/Renderer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BlackjackAI.dir/build.make CMakeFiles/BlackjackAI.dir/src/Renderer.cpp.o
.PHONY : src/Renderer.cpp.o

src/Renderer.i: src/Renderer.cpp.i
.PHONY : src/Renderer.i

# target to preprocess a source file
src/Renderer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BlackjackAI.dir/build.make CMakeFiles/BlackjackAI.dir/src/Renderer.cpp.i
.PHONY : src/Renderer.cpp.i

src/Renderer.s: src/Renderer.cpp.s
.PHONY : src/Renderer.s

# target to generate assembly for a file
src/Renderer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BlackjackAI.dir/build.make CMakeFiles/BlackjackAI.dir/src/Renderer.cpp.s
.PHONY : src/Renderer.cpp.s

src/Trainer.o: src/Trainer.cpp.o
.PHONY : src/Trainer.o

# target to build an object file
src/Trainer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BlackjackAI.dir/build.make CMakeFiles/BlackjackAI.dir/src/Trainer.cpp.o
.PHONY : src/Trainer.cpp.o

src/Trainer.i: src/Trainer.cpp.i
.PHONY : src/Trainer.i

# target to preprocess a source file
src/Trainer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BlackjackAI.dir/build.make CMakeFiles/BlackjackAI.dir/src/Trainer.cpp.i
.PHONY : src/Trainer.cpp.i

src/Trainer.s: src/Trainer.cpp.s
.PHONY : src/Trainer.s

# target to generate assembly for a file
src/Trainer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BlackjackAI.dir/build.make CMakeFiles/BlackjackAI.dir/src/Trainer.cpp.s
.PHONY : src/Trainer.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BlackjackAI.dir/build.make CMakeFiles/BlackjackAI.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BlackjackAI.dir/build.make CMakeFiles/BlackjackAI.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BlackjackAI.dir/build.make CMakeFiles/BlackjackAI.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... BlackjackAI"
	@echo "... src/Card.o"
	@echo "... src/Card.i"
	@echo "... src/Card.s"
	@echo "... src/Deck.o"
	@echo "... src/Deck.i"
	@echo "... src/Deck.s"
	@echo "... src/Hand.o"
	@echo "... src/Hand.i"
	@echo "... src/Hand.s"
	@echo "... src/QLearner.o"
	@echo "... src/QLearner.i"
	@echo "... src/QLearner.s"
	@echo "... src/Renderer.o"
	@echo "... src/Renderer.i"
	@echo "... src/Renderer.s"
	@echo "... src/Trainer.o"
	@echo "... src/Trainer.i"
	@echo "... src/Trainer.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

